### ISSUE TITLE
Please release version with updated dependencies in master

### ISSUE THREAD

**Issue by justinstoller** [clj-commons/fs#4]
We use raynes/fs 1.4.6 and had to upgrade apache's compress lib for other reasons. This removed the implicit dependency on xz and broke us.

We can override as necessary locally, but it would be great to have a release that pulled in a modern compress and expressed the dependency on xz explicitly (as you have done in master).

Is there any work that I could do to help with the release process?

**Comment by slipset** [comment]
1.5.1 is released to clojars. Please let me know if there are any issues.

**Comment by justinstoller** [comment]
Thanks!
