### ISSUE TITLE
Drop support for Java 7 going forward

### ISSUE THREAD

**Issue by borkdude** [clj-commons/fs#7]
I think we can get rid of this macro going forward:

https://github.com/clj-commons/fs/blob/642e0e6fc734b0855a4579d4518073b2192ac0ef/src/me/raynes/fs.clj#L156

and drop support for Java 7 in future versions.

**Comment by danielcompton** [comment]
Looking at that macro, I think the purpose was to enable support for Java 7 functions if you were on Java 6 or older, which reached EOL in October 2013

> Java 6 reached the end of its supported life in February 2013, at which time all public updates, including security updates, were scheduled to be stopped. https://en.wikipedia.org/wiki/Java_version_history#Java_SE_6

This seems Ok to me, unless someone really wants us to support it.
